services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
 
    App\Service\AuthenticationServiceInterface: '@App\Service\AuthenticationService'

    App\Service\AxiomService:
        arguments:
            $url: '%env(AXIOM_URL)%'
            $token: '%env(AXIOM_TOKEN)%'


    App\Service\TraceIdGenerator:
        shared: true  

