services:
  - type: web
    name: open-hub-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: VITE_API_URL
        value: https://open-hub-backend.onrender.com
      - key: REACT_APP_API_URL
        value: https://open-hub-backend.onrender.com

  - type: web
    name: open-hub-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: JWT_PASSPHRASE
        sync: false
      - key: JWT_PRIVATE_KEY
        sync: false
      - key: JWT_PUBLIC_KEY
        sync: false
      - key: CORS_ALLOW_ORIGIN
        value: https://open-hub-frontend.onrender.com
      - key: TRUSTED_PROXIES
        value: REMOTE_ADDR
      - key: APACHE_DOCUMENT_ROOT
        value: /opt/render/project/src/backend/public
      - key: OTEL_EXPORTER_OTLP_ENDPOINT
        value: https://ton-jaeger.onrender.com:4318
      - key: OTEL_SERVICE_NAME
        value: open-hub-backend
      - key: OTEL_TRACES_EXPORTER
        value: otlp
      - key: AXIOM_TOKEN
        sync: false
      - key: AXIOM_URL
        value: https://logs.collector.eu-01.cloud.solarwinds.com/v1/logs


  - type: web
    name: open-hub-prometheus
    env: docker
    plan: free
    dockerfilePath: ./prometheus/Dockerfile
    dockerContext: ./prometheus
    envVars:
      - key: BACKEND_URL
        value: https://open-hub-backend.onrender.com
      - key: GRAFANA_TOKEN 
        sync: false