services:
  - type: web
    name: openhub-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    buildArgs:
      VITE_API_URL: https://openhub-backend.onrender.com
    envVars:
      - key: VITE_API_URL
        value: https://openhub-backend.onrender.com
      - key: REACT_APP_API_URL
        value: https://openhub-backend.onrender.com

  - type: web
    name: openhub-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: JWT_PASSPHRASE
        sync: false
      - key: CORS_ALLOW_ORIGIN
        value: https://openhub-frontend.onrender.com
      - key: TRUSTED_PROXIES
        value: REMOTE_ADDR
      - key: APACHE_DOCUMENT_ROOT
        value: /opt/render/project/src/backend/public
      - key: OTEL_EXPORTER_OTLP_ENDPOINT
        value: https://ton-jaeger.onrender.com:4318
      - key: OTEL_SERVICE_NAME
        value: openhub-backend
      - key: OTEL_TRACES_EXPORTER
        value: otlp
      - key: PAPERTRAIL_TOKEN
        sync: false
      - key: PAPERTRAIL_URL
        sync: false

  - type: web
    name: openhub-prometheus
    env: docker
    dockerfilePath: ./prometheus/Dockerfile
    envVars:
      - key: BACKEND_URL
        value: https://openhub-backend.onrender.com