
security:
    password_hashers:
        App\Entity\User:
            cost: 4 # pour les tests, à augmenter en production !
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login_check
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/, requires_channel: https }
        - { path: ^/metrics/frontend/collect, roles: PUBLIC_ACCESS }
        - { path: ^/metrics/backend/collect, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/api/frontend-metrics, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/test, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/test/papertrail, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/donate, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }