FROM php:8.3-apache

RUN apt-get update && apt-get install -y \
    git unzip libicu-dev libzip-dev libpng-dev zip \
    libonig-dev curl && \
    docker-php-ext-install intl pdo pdo_mysql gd zip opcache mbstring && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN a2enmod rewrite headers

WORKDIR /var/www/html

COPY . .

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install --no-dev --optimize-autoloader --no-scripts

# Configure Apache
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf


RUN mkdir -p /etc/secrets
ENV JWT_PRIVATE_KEY_PATH=/etc/secrets/private.pem
ENV JWT_PUBLIC_KEY_PATH=/etc/secrets/public.pem


EXPOSE 80
CMD php bin/console cache:clear --no-warmup && apache2-foreground

echo "$JWT_PRIVATE_KEY" > /etc/secrets/private.pem && \
echo "$JWT_PUBLIC_KEY" > /etc/secrets/public.pem && \
apache2-foreground

CMD ["apache2-foreground"]