# Étape de build
FROM php:8.2-apache

# Installe Composer
RUN apt-get update && apt-get install -y git unzip libicu-dev libzip-dev zip \
    && docker-php-ext-install intl pdo pdo_mysql zip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html

# Copie des fichiers du projet
COPY . .

# Désactive les scripts post-install (comme cache:clear)
RUN composer install --no-dev --optimize-autoloader --no-scripts

# Copie la configuration Apache
COPY ./docker/apache/vhost.conf /etc/apache2/sites-available/000-default.conf

RUN a2enmod rewrite

EXPOSE 80

# Commande de démarrage
CMD ["apache2-foreground"]
