name: Auto-Update README

on:
  push:
    paths:
      - 'backend/composer.json'
      - 'backend/.env'
      - 'README.template.md'
      - 'backend/bin/generate-readme.sh'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate README
        run: |
          chmod +x backend/bin/generate-readme.sh
          ./backend/bin/generate-readme.sh
      
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: auto-update README"
          git push