lexik_jwt_authentication:
    secret_key: MIIJtTBfBgkqhkiG9w0BBQ0wUjAxBgkqhkiG9w0BBQwwJAQQjGqkfitW2gOn02uj
Q8FBDgICCAAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEGs6Cnr5ZbWOo4kO
8u5kEaUEgglQj7XHcWo0ZXTlARWStnB4+1Cp9seu8U4mG3bk64cE0TDyMRCcTEjv
C6Fo9rDW5lZtPLIoJxifFkkiW/d7DrQKIu3irCJSkINW5Rj47jwysY53SHUrfi2+
XFHw65Fkq+YOUbtCyGf8iaU8RWVUV3TzmktPyyC5msSf01DMDAigdIv0xkJ1xW4K
mSvYLpmh1N/67gs2JzosICyyMObWXbGnAIEksuFJlibjoIzwC3xVe+x2wxPVjLXq
rg/vEHASvA7iaDEkUCiaHeAfYhKzXW4ePHP/E1P1wKejBwWHQHEV9TmpzOqdCdw2
5MKfEs+J+G5ca1aHylI/SlRlP/y1s4Lk9x66ZR/JTh5DOwJ7Ct8ABaQMScNBS4fC
01kGvzA6JoYPfbouILbfbfTtsqdy1ZmstJdiSeci5qJ32xTYovUigYuyQ840xy2p
R4w0xWrMcEAW5vMyImB1hpodNm1U/Mu3Bf4ccGK0No67tiBLRGdYSIMdbiQ7JuOS
cuuYfTngfk2c2xDy4qjXhXp7wu7ZOcjlxhtdyBqwtH8Lb9vikZIVHsjKN7SaaHtW
PMBJsETJJoYIbRlu1rtQfd8WaExI6XiX/MUT4PsuYB5O/cDtfQkNYGGrRnkb1K9l
l06l2YVspkKw/NLChHwjD4rIq46X0h24fbp03wveQgpgucuwJt1hwbbBCPSya+RK
92VkLB7p7W3nU9fNraX/msCO+ngapoKke+bO2Gq+0T7Y8hX4Wx+o8nMh7da4ba4m
mhYxBe3FWGE1aLTsJdDQdo229oSPAYv6K/2GWrYkwUnkDcX+CpzgIy/KfTWAWpsc
fME0zeWC/UB30L7hHnzdf5+p0fmFgb/CkZm/TAEMg9CW/1JUvfnanjkqDTRaYXAH
emU9/ugKjFFKzXXuRL7btIT+vCl3dHscmFcWuvx5xwJyOeAAZGA0Rx3Qy22l06nE
xbAkCow7JaKHqXVhrdyIcmR6vI04F5DKJDpp2ZLQ1+7kpekzjKB69jTHuDRXcbft
ULld6dkxyeZ25PFZC+sLi7i6Dfh0vz6LtQD4tmoHwp0kSROgLdd8b+XGH0lk+7Od
hxRAZYwLhHwur6QygZe5qtp/7FtY1xL1XnesPb0kFdyXZI0nOnfleXxTauZNrxEX
8KOuzRBXFO3Xae9Eu4GLjWlgjjW2naIzMxNByfcRYoCEWv+i1wLLeKivwS6DOLwl
WGNyISDDYkQXDM2RlPYEKPgwehvSVMF9RClZ58MWerNAuLxvWFbraMmUeTvoOe06
kDPqzrtz7gwatJiGJZxXcWmxh7YBsXWm5feqJf6H6AGo1zvGwJQ1z8YQPpMvQrAP
OOvij6gAH0FO8DKNYkltuP8lmI+O+6Tg/db4z+Jsk6DIsKPhXYmwcSeN/7gdoQjn
sOa3/IfmtmkwJF9657EkWaGTWRqyTj5Nd7XpVpPXcXuuKYKLYfjJ7ii/AxFuovjd
+HLKZOk5ZmpI0AmJs0cF8QY74fMHQdkG01xHmNR9CZEcwa3D/1arD94G4Y4PJXx6
7Thw4KRIKhWBNMuXrnHbN8GIQ+u0yc9+2Z7XAX6tDkW4xh90LqBDL567P/+eOrCv
+PN1iay8POgnC+TQDQgsCu6c5pb9ZhkA7R2ITY4yz3yotCDMWGFhoqIdjFk75uDW
hxZBS6NODOY4MaVi396+X3nf59q8K7PNTAfUjBlakP+NEaUy4L4BQyq05nmmxTFm
xMQHVU3dIlHhnYtSWdHjaLjCE2N6zSICpLZqQ2GfT0Z85OPuEkJDhFO4/k2xm0Gd
mxPKMQQ9MKB0qYCyq64SsnGt4x1CkoFl+c3X83jwJwjD+b8kcTTMlosBNapvj0/I
pszPljkIxzA6hcMCugGbh5Z7nx8LiRnF+mzzIBSjS6H9meDxxY+6VfhJqJLq6LU6
dlt17msgF30UGE49SDB3oXktZnGU5pjvZAmhoRgmMTJGbpyTEEPMuOT4840YjICo
Ug+ifBSM0OFAzleIMMes4un4xTxO+hinRFpg0xDazd9LqJv+rhJeA6Hwe6A6SpCa
f3C/RRa0oduh/cDWgF2v4uGIyGed0mE9BV1Zdrf7HLjhiEAA9SmM18nbCBcroN5X
TSGMHa3mxwQrNvP9WUFgUpLhMQ6aXZ/DprekVvNKJPnAPr2m+VinDAFDalOf/pxK
7MtugGo1eBV9giuYcLVkKQNGlF6GJYcB8H1ffhrnETwi3hQedeh3fsi4JEBdf44H
3We5bx9bfSaMHWFx7tTY5ACAG+ufHe8yU6EipOGeyogT9RNoQAjlBWUlPPDCR+nv
vsdIpNNHZRS7o6stZS6h3hFFr6F20q/NIWQ/9Yv5TWu3OjYeAumfxifzzpodKCAq
o1Pb7P4rES4W27MCQ4Xq2H5iCcfa2RsTOU2QwFNlCJlONXstf1yGv4XXddhvgSuT
7r8/WBV51r56Z4PQ+hPOW1ioTlg2HirAMCNHMa1wjPcAGoBwYSEZ+yzjySu8EwRA
aLGLWQ1CsLIXRMbbhFh8rm9wncLTxQK+8UgvcQ2kTPiPEwNAMHOecmROIASDy1hL
LoqjECEdgTU2cnbANKEXV7+4h7tS+b+tV5ZhCP6xzsFdLH1AGfaSzOvFMgtOiC04
RWzkSHLXmeK/6L5/1I3ichHGRIgYZuMjei5FoyQHMCNypbIkE7JiALOURP8UY8Xo
gibBES6tYoJ0+oV+nqBZ3SMUIQJrLGkEjyfCctwPRyIclGUgYtcqD3bnuBIaQDdQ
9I1pZ2CU9olnfOw+Ox4EDQcCuUI7N5rRBGnSP2iEDBuhzYyxr198/gfRBVcEH52y
U6U/odX9G1+iQqkZ/3LjWmfeRVpnRa2YRSyQd4SZjR03gA2BGUxqQ+QVw0A0FE/Y
hs6REEW0K2PEq40PCMCJk+lJqXpmlXugrbryfrNaVnUE3joMPkZtta3HSLVcSEXn
fzqcNPyd29T9IdNPdcaDfUcvWrn23DimYGwCvFcPg0kSvxgFw47gtxwyS2WWj345
P9QR8iOHxb5phZ8WMuirTfZvWdVyk446DAQ6ONR0gF86sZXlpB4lrpfvO8znw1WC
qxB8RJ5pmfnAtxhCp4pg1jv4UeFuFgV4OBkSiWUwyY7xUkOeiyq4pMEF7CS5VhXZ
8MWTBq4YN3hj9GTueM3W5NLNtPtTYRhGN4w1Hk7/FHlVQ43Iz6xSQ5A=
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
