services:
 
    App\Service\AuthenticationServiceInterface: '@App\Service\AuthenticationService'

    App\Security\LoginSuccessHandler:
        public: true

    App\Security\LoginFailureHandler:
        public: true

    App\Security\ApiTokenAuthenticator:
        arguments:
            $someDependency: '@some_dependency'

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'